name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          cache: pip
          cache-dependency-path: requirements_test.txt

      - name: Install the test requirements
        run: pip install -r requirements_test.txt

      - name: Run the tests
        run: pytest --cov=custom_components/lk_ihc --cov-report=term-missing
